language: go
sudo: false
go:
  - 1.6
  - 1.7
  - master


before_install:
  - go get github.com/BurntSushi/toml
  - go get github.com/Sirupsen/logrus
  - go get github.com/coocood/freecache
  - go get github.com/spaolacci/murmur3
  - go get github.com/miekg/dns

script:
  - go test -v ./...
