language: go
go_import_path: github.com/oif/proton
sudo: false
go:
  - 1.6
  - 1.7
  - master

before_install:
  - cp -r ../proton $HOME/gopath/src
  - cd $HOME/gopath/src/proton

script:
  - go test -v ./...
