language: go
sudo: false
go:
  - 1.6
  - 1.7
  - master

before_install:
  # don't use the miekg/dns when testing forks
  - mkdir -p $GOPATH/src/github.com/oif
  - ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/oif/ || true

script:
  - go test -race -v -bench=.